# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_profile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
